### ISSUE TITLE
Hangs on FCI-Max with Fisher Z test

### ISSUE THREAD

**Issue by marissadi** [bd2kccd/causal-cmd#67]
Hi, I was trying to run the following command:

```
java -jar causal-cmd-1.3.0/causal-cmd-1.3.0-jar-with-dependencies.jar --dataset data.txt --algorithm fcimax --alpha 0.001 --data-type continuous --delimiter tab --test fisher-z-test --out $outdir --prefix output --verbose Yes --skip-latest
```
on a dataset with 50 variables and 100 samples. This does run on the same data if I use `cci-test` for the test option, but when I change to `fisher-z-test` it will hang for days and not give an output, just with the last line of the output remaining "Independence accepted: [...]" This occurs across different alpha values as well. 

How do I troubleshoot what is going on?

**Comment by marissadi** [comment]
Actually, it looks like this also sometimes occurs with `cci-test` when I run it with alpha 0.5, although I don't know if it's the same issue.

**Comment by jdramsey** [comment]
Not sure. CCI I can understand, but Fisher Z I don't yet. (CCI is a more complex test.)

I don't generally use the command line tool. I wonder if I can reproduce this programmatically? Any suggestions?

**Comment by jdramsey** [comment]
@marissadi This is a very old issue at this point; if it's something you're still having problems with I could try to address it. (Normally I work in Tetrad, but I'm more familiar with causal-cmd now so I think I'd be able to spot such problems at this point.)

I should point out of course that we've released new versions of both Tetrad and causal-cmd since your issue was posted. The current version of causal-cmd is 1.5.0; we're planning to release an additional update to both Tetrad and causal-cmd very soon.

**Comment by jdramsey** [comment]
@marissadi I'm going to close this issue for now since it's gone stale, but if you're still having the problem or if you're having new problem with it feel free to re-open the issue or make a new one. I'm not having any trouble at all with FCI-Max with Fisher Z, so I can't reproduce that. CCI is of course a more general test (and hence much slower) so I can see why there ar e problem there. 

But please if there's still an issue re-open this.
